apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-cluster-master-0
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redis-cluster-master-0